service: pharma-serverless

custom:
  patientTableName: PatientTable
  adminUserTableName: AdminUserTable

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.patientTableName}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.adminUserTableName}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

# DynamoDB config
resources:
  Resources:
    PatientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.patientTableName}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    AdminUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.adminUserTableName}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getPatients:
    handler: src/patient-handler.getPatients
    events:
      - http:
          path: /patients
          method: get
          cors: true
          authorizer: adminAuthorizer
  savePatient:
    handler: src/patient-handler.savePatient
    events:
      - http:
          path: /patients
          method: post
          cors: true
          authorizer: adminAuthorizer
  signup:
    handler: src/auth-handler.signup
    events:
      - http:
          path: /signup
          method: post
          cors: true
  login:
    handler: src/auth-handler.login
    events:
      - http:
          path: /login
          method: post
          cors: true
  checkToken:
    handler: src/auth-handler.checkToken
    events:
      - http:
          path: /check-token
          method: get
          cors: true
  adminAuthorizer:
    handler: src/auth-handler.authorize


# Ignored Files
package:
  exclude:
    - '.idea/**'
    - 'src/**/*.test.js'
    - '*Docker*'
    - '*docker*'
    - '.dynamodb/**'
